spring:
  data:
    mongodb:
      uri: mongodb+srv://springMongoUser:${MONGODB_PASSWORD}@prodcluster0.bdjwu.mongodb.net/beacon-cis-prod?retryWrites=true&w=majority
do:
  spaces:
    key: ${DO_SPACES_KEY}
    secret: ${DO_SPACES_SECRET}