spring:
  data:
    mongodb:
      uri: mongodb+srv://springMongoUser:${MONGODB_PASSWORD}@beacon-east.lw78i.mongodb.net/beacon-cis-main-staging?retryWrites=true&w=majority
do:
  spaces:
    key: ${DO_SPACES_KEY}
    secret: ${DO_SPACES_SECRET}