---
openapi: 3.0.1
tags:
  - name: Tower Management
    description: Join, create, edit, and delete Towers
info:
  title: Beacon City API
  version: '@version@'
  description: |
    This is the API for the City component of the Beacon backend.
    A City is a service that may host one or more Towers.

servers:
  - url: 'http://localhost:8080'
    description: localhost
  - url: 'https://beacon-city-main-staging.herokuapp.com'
    description: Main branch
  - url: 'https://beacon-city.herokuapp.com'
    description: Production

paths:
  '/hello-world':
    get:
      tags: [SampleText]
      description: Says "Hello, world!"
      operationId: helloWorld
      responses:
        '200':
          description: Ok. Operation Successful

#------------------------------------------------------------------------
# Components
#------------------------------------------------------------------------
components:

  #----------------------------------------------------------------------
  # Security Schemes
  #----------------------------------------------------------------------
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic

  #----------------------------------------------------------------------
  # Parameter
  #----------------------------------------------------------------------
  parameters:
    $ref: "./parameters/_index.yaml"

  #----------------------------------------------------------------------
  # Schema
  #----------------------------------------------------------------------
  schemas:
    $ref: "./schemas/_index.yaml"

  #----------------------------------------------------------------------
  # Response
  #----------------------------------------------------------------------
  responses:
    $ref: "./responses/_index.yaml"

#------------------------------------------------------------------------
# Security
#------------------------------------------------------------------------
security:
  - basicAuth: [ ]
