spring:
  data:
    mongodb:
      uri: mongodb+srv://springMongoUser:${MONGODB_PASSWORD}@beacon-east.lw78i.mongodb.net/beacon-city-main-staging?retryWrites=true&w=majority
city:
  cis-url: https://beacon-cis-main-staging.herokuapp.com
  hostname: beacon-city-main-staging.herokuapp.com
do:
  spaces:
    key: ${DO_SPACES_KEY}
    secret: ${DO_SPACES_SECRET}
    endpoint: nyc3.digitaloceanspaces.com
    region: nyc3
    bucket: beaconcdn
