name: Build and Release
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
      - uses: actions/setup-java@v2
        with:
          distribution: liberica
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle createRelease
        # Ordinarily I'd just run the release command and let Gradle handle making and pushing tags. However, https://github.com/allegro/axion-release-plugin/issues/401 causes an issue because JGit can't use newer SSH keys.
        # This command will make the git tag.
        run: ./gradlew createRelease
      - name: Execute Gradle build
        run: ./gradlew build
      - name: Push the new tag
        run: NEW_TAG=$(git tag) && echo Preparing to push new tag "'$NEW_TAG'" && git push origin $NEW_TAG

      - name: Publish client lib for Central Identity Server
        run: npm publish ./central-identity-server/build/openapi/generated-client-source
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish client lib for City
        run: npm publish ./city/build/openapi/generated-client-source
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
