name: Build and Release
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: liberica
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew build
      - name: Upload code coverage (common module)
        uses: codecov/codecov-action@v2
        with:
          files: ./common/build/reports/jacoco/test/jacocoTestReport.xml
          flags: common
          name: Common
      - name: Upload code coverage (Central Identity Server)
        uses: codecov/codecov-action@v2
        with:
          files: ./central-identity-server/build/reports/jacoco/test/jacocoTestReport.xml
          flags: cis
          name: Central Identity Server
      - name: Upload code coverage (City)
        uses: codecov/codecov-action@v2
        with:
          files: ./city/build/reports/jacoco/test/jacocoTestReport.xml
          flags: city
          name: City
      - name: Execute Gradle createRelease
        # Ordinarily I'd just run the release command and let Gradle handle making and pushing tags. However, https://github.com/allegro/axion-release-plugin/issues/401 causes an issue because JGit can't use newer SSH keys.
        # This command will make the git tag.
        run: ./gradlew createRelease
      - name: Push the new tag
        run: NEW_TAG=$(git tag) && echo Preparing to push new tag "'$NEW_TAG'" && git push origin $NEW_TAG
